server:
  port: 7001

spring:
  datasource:

    url: jdbc:mysql://3.38.106.51:3306/aitalk_web?useSSL=false&serverTimezone=Asia/Seoul
    username: dongsil
    password: dongsil

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # MyBatis를 사용하므로 JPA 자동 테이블 생성 비활성화
    show-sql: true

  mail:  # ✉️ 이메일 설정 추가
    host: smtp.gmail.com
    port: 587
    username: kimtest7001@gmail.com  # 📌 본인의 Gmail 주소 입력
    password: hqoi sbve jxif ffmu  # 📌 "앱 비밀번호" 입력
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.ssafy.aitalk.user.dto
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: MDEyMzQ1Njc4OWFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MTIzNA==
  expiration: 86400000  # 1일 (밀리초 단위)
